name: Deploy

on:
  push:
    branches:
      - main

jobs:

  create-envfile:
    name: Create Env File
    runs-on: ubuntu-latest

    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.2
      with:
        envkey_VITE_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        envkey_VITE_DISCORD_BOT_LINK: ${{ secrets.DISCORD_BOT_LINK }}
        envkey_VITE_GOOGLE_SHEETS_API: ${{ secrets.GOOGLE_SHEETS_API }}
        envkey_VITE_IMGUR_API: ${{ secrets.IMGUR_API }}
        file_name: .env
        fail_on_empty: false

  build:
    name: Build
    needs: create-envfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist